spring:
  application:
    name: SpringBank

  datasource:
    url: jdbc:postgresql://localhost:5432/BankApp
    username: postgres
    password: 01032002ama
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring doc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ImbBFh2MzRiitDhOaf0vOwqLiuUAich3DWYrCdq2ltkvgSSG9xEN0PJs3qaX9Wvg82A5VNaKo24065TqU7tOzN
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 604800000